### ISSUE TITLE
[Documentation] Unknown input field

### ISSUE THREAD

**Issue by rowild** [AOEpeople/TYPO3_RestlerExamples#6]
The documentation explains:
`[...] Add the extension key restler_example at the end of the "TYPO3-Extensions with required ext_localconf.php-files" input field.`

I have never ever seen such an input field, and it seems the restler ext does not provide one either. Where exactly do I have to look for that field?

Thank you!

**Comment by felixsemmler** [comment]
Thanks for your response. This part of the documentation is outdated and can be ignored. I will remove this from the documentation. In 2018 we removed this TYPO3 configuration from the restler extension because it is not needed anymore. In a very previous version of the restler extension, which was compatible with TYPO3 6.x, we had a performance issue, because the whole TYPO3 was bootstrapped (all extensions) for every request, which was a big bottleneck.

All you had to do is to install the `restler` and `restler_examples` extension with composer for instance.

**Comment by felixsemmler** [comment]
I release a new version of the restler_examples extension where I dropped this part of the outdated documentation.

https://extensions.typo3.org/extension/restler_examples
https://packagist.org/packages/aoe/restler-examples
